# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726ab1dd93773fe5a2ea7c394f2113bec58df4d010307808bf970b11564e0c00c546fc20d1ff865be542309fe6c0de13beacb49be41efd3cea626d8a699f0fec

test:
  secret_key_base: 13eb831874ccc5f6c5e656606d0e7bb937c99ef4a866ae6f2ddf55fffded2e615f620870a82b160e5db7f55c60c0128e82125543adebc0a8a4eaac7a609ff63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
